import "server-only";

import { createCipheriv, createDecipheriv, randomBytes, timingSafeEqual } from "node:crypto";

import { hashCapabilityToken, isWellFormedCapabilityToken } from "@/lib/security/capability-token";

/**
 * Recoverable RSVP capability (LB-13, ADR-006): the encrypted copy of a
 * GuestInvitation's current link token, so the server can show organizers
 * the SAME link again later. Pure crypto: no database, no React, no
 * Supabase, no logging.
 *
 * - The SHA-256 `token_hash` stays the ONLY validator of incoming guest
 *   links. This envelope is never consulted on the guest request path.
 * - AES-256-GCM (Node's built-in crypto), a fresh 96-bit random IV per
 *   encryption, the 128-bit GCM tag, and associated data binding the
 *   envelope to the token hash it belongs to
 *   (`listalaboda:rsvp-capability:v1:<tokenHash>`).
 * - Envelope: `v1.<iv>.<ciphertext>.<tag>`, each part base64url without
 *   padding. Parsed strictly; anything else is refused before decrypting.
 * - The 256-bit key comes only from the server environment
 *   (`RSVP_CAPABILITY_ENCRYPTION_KEY`, base64url of exactly 32 bytes) and
 *   is never stored in PostgreSQL, generated by the app, logged or echoed.
 *   Losing or changing it makes stored envelopes unrecoverable; it never
 *   invalidates the guest links themselves.
 *
 * Every decryption failure (wrong key, tampering, wrong binding, malformed
 * input) is the same `null`: callers must not tell them apart.
 */

const ALGORITHM = "aes-256-gcm";
const VERSION = "v1";
const KEY_BYTES = 32;
const IV_BYTES = 12;
const TAG_BYTES = 16;
/** A capability token is 43 ASCII characters; GCM ciphertext has the same length. */
const CIPHERTEXT_BYTES = 43;
const TOKEN_HASH_PATTERN = /^[0-9a-f]{64}$/;
const BASE64URL_PATTERN = /^[A-Za-z0-9_-]+$/;

/** Upper bound for a stored envelope (the database CHECK mirrors the exact v1 shape). */
export const RSVP_CAPABILITY_ENVELOPE_MAX_LENGTH = 200;

export type RsvpCapabilityEncryptionSettings = Readonly<{ key: Buffer }>;

export type RsvpCapabilityEncryptionSettingsResult =
  | Readonly<{ ok: true; settings: RsvpCapabilityEncryptionSettings }>
  | Readonly<{ ok: false; problem: "missing" | "invalid" }>;

type EnvSource = Readonly<Record<string, string | undefined>>;

/**
 * Strict base64url (no padding, canonical): re-encoding must give back the
 * exact input, so stray characters or non-zero trailing bits are refused.
 */
function decodeBase64url(value: string, bytes: number): Buffer | null {
  if (!BASE64URL_PATTERN.test(value)) return null;
  const decoded = Buffer.from(value, "base64url");
  if (decoded.length !== bytes || decoded.toString("base64url") !== value) return null;
  return decoded;
}

/**
 * Pure: validates the key setting. No trimming — a whitespace-corrupted
 * value is refused, not repaired. There is no fallback and no generated
 * key: a key made up at boot would strand every envelope written with it.
 */
export function parseRsvpCapabilityEncryptionSettings(
  source: EnvSource,
): RsvpCapabilityEncryptionSettingsResult {
  const raw = source.RSVP_CAPABILITY_ENCRYPTION_KEY;
  if (raw === undefined || raw === "") return { ok: false, problem: "missing" };
  const key = decodeBase64url(raw, KEY_BYTES);
  if (!key) return { ok: false, problem: "invalid" };
  return { ok: true, settings: Object.freeze({ key }) };
}

/** Reads the key from `process.env` (server only; the one place that does). */
export function getRsvpCapabilityEncryptionSettings(): RsvpCapabilityEncryptionSettingsResult {
  return parseRsvpCapabilityEncryptionSettings({
    RSVP_CAPABILITY_ENCRYPTION_KEY: process.env.RSVP_CAPABILITY_ENCRYPTION_KEY,
  });
}

function associatedData(tokenHash: string): Buffer {
  return Buffer.from(`listalaboda:rsvp-capability:${VERSION}:${tokenHash}`, "utf8");
}

function sameHash(a: string, b: string): boolean {
  if (!TOKEN_HASH_PATTERN.test(a) || !TOKEN_HASH_PATTERN.test(b)) return false;
  return timingSafeEqual(Buffer.from(a, "hex"), Buffer.from(b, "hex"));
}

/**
 * Encrypts a freshly generated token for storage next to its hash. Throws
 * (without echoing anything) on inconsistent input, so a caller can't
 * persist an envelope that doesn't belong to the hash it stores.
 */
export function encryptRsvpCapability(
  input: Readonly<{ token: string; tokenHash: string; key: Buffer }>,
): string {
  const { token, tokenHash, key } = input;
  if (key.length !== KEY_BYTES) throw new Error("Invalid RSVP capability encryption key.");
  if (!isWellFormedCapabilityToken(token) || !sameHash(hashCapabilityToken(token), tokenHash)) {
    throw new Error("RSVP capability does not match its hash.");
  }
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv, { authTagLength: TAG_BYTES });
  cipher.setAAD(associatedData(tokenHash));
  const ciphertext = Buffer.concat([cipher.update(token, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return [VERSION, iv, ciphertext, tag]
    .map((part) => (typeof part === "string" ? part : part.toString("base64url")))
    .join(".");
}

type ParsedEnvelope = Readonly<{ iv: Buffer; ciphertext: Buffer; tag: Buffer }>;

function parseEnvelope(envelope: string): ParsedEnvelope | null {
  if (envelope.length > RSVP_CAPABILITY_ENVELOPE_MAX_LENGTH) return null;
  const parts = envelope.split(".");
  if (parts.length !== 4 || parts[0] !== VERSION) return null;
  const iv = decodeBase64url(parts[1], IV_BYTES);
  const ciphertext = decodeBase64url(parts[2], CIPHERTEXT_BYTES);
  const tag = decodeBase64url(parts[3], TAG_BYTES);
  if (!iv || !ciphertext || !tag) return null;
  return { iv, ciphertext, tag };
}

/** Shape check only (version, parts, lengths); proves nothing cryptographically. */
export function isWellFormedRsvpCapabilityEnvelope(envelope: string): boolean {
  return parseEnvelope(envelope) !== null;
}

/**
 * Recovers the plaintext token, or `null` for ANY failure: malformed
 * envelope, wrong key, tampered IV/ciphertext/tag, an envelope bound to
 * another hash, or a plaintext that isn't a token hashing to
 * `expectedTokenHash` (the party's CURRENT hash). Never throws.
 */
export function decryptRsvpCapability(
  input: Readonly<{ envelope: string; expectedTokenHash: string; key: Buffer }>,
): string | null {
  const { envelope, expectedTokenHash, key } = input;
  if (key.length !== KEY_BYTES || !TOKEN_HASH_PATTERN.test(expectedTokenHash)) return null;
  const parsed = parseEnvelope(envelope);
  if (!parsed) return null;

  let token: string;
  try {
    const decipher = createDecipheriv(ALGORITHM, key, parsed.iv, { authTagLength: TAG_BYTES });
    decipher.setAAD(associatedData(expectedTokenHash));
    decipher.setAuthTag(parsed.tag);
    token = Buffer.concat([decipher.update(parsed.ciphertext), decipher.final()]).toString("utf8");
  } catch {
    return null;
  }
  if (!isWellFormedCapabilityToken(token)) return null;
  return sameHash(hashCapabilityToken(token), expectedTokenHash) ? token : null;
}
